name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        with:
          version: latest
          verb: checks

  # build:
  #   runs-on: ubuntu-latest
  #   needs: checks
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
  #       with:
  #         version: latest
  #         verb: call
  #         args: build
